spring:
  datasource:
    url: jdbc:mysql://111.229.198.213:3306/ende_shengtai?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456

upload:
  imgSavePath: "/usr/local/upload"
  fileSavePath: "/usr/local/upload"
share:
  urlSuffix: http://dt-information.cn
