spring:
  datasource:
    url: jdbc:mysql://58.250.17.31:3345/ende?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1015tqljsw
  redis:
    host: 192.168.1.134
    password: 123
upload:
  imgSavePath: "C:/upload/img"
  fileSavePath: "C:/upload/file"
share:
  urlSuffix: http://192.168.1.134:9093
